default_install_hook_types:
  - pre-commit

repos:
  - repo: local
    hooks:
      - id: make-format
        name: make format
        entry: make format
        language: system
        pass_filenames: false
      - id: make-check
        name: make check
        entry: make check
        language: system
        pass_filenames: false
