[project]
name = "custom-echo-soul"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["kimi-cli", "kosong"]

[tool.uv.sources]
kimi-cli = { path = "../../" }
